### ISSUE TITLE
Question Display: Support Markdown

### ISSUE THREAD

**Issue by shotaronowhere** [RealityETH/reality-eth-monorepo#83]
Questions [may](https://realityeth.github.io/#!/question/0xdf33060f476f8cff7511f806c72719394da1ad64-0x54e6922b7bca58516225cccfaeaf206b219250b651989f36b05e6c5d25e97b17) refer to ipfs hosted documents / rules which contain long content ids which do not display well in the UI.

The question formatting should support markdown so (long) URLs can be represented by (short) hyperlinks and more generally to allow more format customization and better question display.

**Comment by edmundedgar** [comment]
I'll look into this. If we support it we probably won't just suddenly start interpreting existing questions are markdown as it may be possible to game it to confuse people about the meaning of questions. At first thought what we might do is one of:
 
 * Add an `is_markdown: true` field to the question json and interpret as markdown if we see it set (defaulting to `false` if it's not there)
 * As above, but make the field something like `formatting: markdown` (defaulting to say `formatting: text` if we don't see it)
 * Keep the title as it is, but support a new field called something like `description` or `description_markdown`

In all these cases you'll need to pass a new template ID when you ask the question, so we won't change the behaviour of eg template `0` which is the current yes/no template.
