### ISSUE TITLE
Rinkeby Testnet Subgraph Syncing Error

### ISSUE THREAD

**Issue by shotaronowhere** [RealityETH/reality-eth-monorepo#87]
Just a heads up, the rinkeby [subgraph](https://thegraph.com/hosted-service/subgraph/realityeth/realityeth-rinkeby) is failing to sync.

Rinkeby will be deprecated soon enough anyways, but just in case you didn't know about it.

**Comment by edmundedgar** [comment]
Thanks, I saw it failing and thought it was just The Graph dropping rinkeby support but checking now it seems like my bug.
